name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
        
    - name: Create environment file
      run: |
        echo "VITE_THIRDWEB_CLIENT_ID=${{ secrets.VITE_THIRDWEB_CLIENT_ID }}" > .env
        echo "VITE_ENVIRONMENT=production" >> .env
        echo "VITE_USE_TESTNET=false" >> .env
        echo "VITE_DEFAULT_CHAIN_ID=8453" >> .env
        echo "VITE_DEMO_CREATOR_ID=1" >> .env
        echo "VITE_DEMO_CREATOR_WALLET=0x479945d7931baC3343967bD0f839f8691E54a66e" >> .env
        echo "VITE_ADMIN_ADDRESSES=${{ secrets.VITE_ADMIN_ADDRESSES || '' }}" >> .env
        echo "VITE_OWNER_ADDRESSES=${{ secrets.VITE_OWNER_ADDRESSES || '' }}" >> .env
        
    - name: Build application
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

